// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieTown.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieTown.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cinema Warszawa",
                            Rows = 8,
                            SeatsPerRow = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cinema Lublin",
                            Rows = 12,
                            SeatsPerRow = 14
                        });
                });

            modelBuilder.Entity("MovieTown.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropImg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterImg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackdropImg = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1800",
                            Cast = "M. McConaughey, Anne Hathaway, Jessica Chastain",
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Duration = "2h 49m",
                            Genre = "Sci-Fi • Adventure",
                            PosterImg = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=800",
                            Rating = "4.9",
                            ReleaseDate = "2014",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 2,
                            BackdropImg = "https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1800",
                            Cast = "Robert Pattinson, Zoë Kravitz, Paul Dano",
                            Description = "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
                            Director = "Matt Reeves",
                            Duration = "2h 56m",
                            Genre = "Action • Crime",
                            PosterImg = "https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=800",
                            Rating = "4.7",
                            ReleaseDate = "2022",
                            Title = "The Batman"
                        },
                        new
                        {
                            Id = 3,
                            BackdropImg = "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1800",
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.",
                            Director = "Christopher Nolan",
                            Duration = "2h 28m",
                            Genre = "Sci-Fi • Action",
                            PosterImg = "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800",
                            Rating = "4.8",
                            ReleaseDate = "2010",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            BackdropImg = "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=1800",
                            Cast = "Ryan Gosling, Harrison Ford, Ana de Armas",
                            Description = "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.",
                            Director = "Denis Villeneuve",
                            Duration = "2h 44m",
                            Genre = "Sci-Fi • Drama",
                            PosterImg = "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=800",
                            Rating = "4.5",
                            ReleaseDate = "2017",
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 5,
                            BackdropImg = "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=1800",
                            Cast = "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
                            Description = "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.",
                            Director = "Todd Phillips",
                            Duration = "2h 02m",
                            Genre = "Crime • Drama",
                            PosterImg = "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=800",
                            Rating = "4.6",
                            ReleaseDate = "2019",
                            Title = "The Joker"
                        },
                        new
                        {
                            Id = 6,
                            BackdropImg = "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=1800",
                            Cast = "Timothée Chalamet, Zendaya, Rebecca Ferguson",
                            Description = "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
                            Director = "Denis Villeneuve",
                            Duration = "2h 46m",
                            Genre = "Sci-Fi • Adventure",
                            PosterImg = "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?q=80&w=800",
                            Rating = "4.9",
                            ReleaseDate = "2024",
                            Title = "Dune: Part Two"
                        },
                        new
                        {
                            Id = 7,
                            BackdropImg = "https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1800",
                            Cast = "Shameik Moore, Hailee Steinfeld, Oscar Isaac",
                            Description = "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.",
                            Director = "Joaquim Dos Santos",
                            Duration = "2h 20m",
                            Genre = "Animation • Action",
                            PosterImg = "https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=800",
                            Rating = "4.9",
                            ReleaseDate = "2023",
                            Title = "Spider-Man: Across Verse"
                        },
                        new
                        {
                            Id = 8,
                            BackdropImg = "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1800",
                            Cast = "Cillian Murphy, Emily Blunt, Matt Damon",
                            Description = "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
                            Director = "Christopher Nolan",
                            Duration = "3h 00m",
                            Genre = "Biography • Drama",
                            PosterImg = "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800",
                            Rating = "4.8",
                            ReleaseDate = "2023",
                            Title = "Oppenheimer"
                        },
                        new
                        {
                            Id = 9,
                            BackdropImg = "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=1800",
                            Cast = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski",
                            Duration = "2h 16m",
                            Genre = "Sci-Fi • Action",
                            PosterImg = "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=800",
                            Rating = "4.7",
                            ReleaseDate = "1999",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 10,
                            BackdropImg = "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=1800",
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            Description = "Greed and class discrimination threaten the symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Director = "Bong Joon Ho",
                            Duration = "2h 12m",
                            Genre = "Drama • Thriller",
                            PosterImg = "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=800",
                            Rating = "4.6",
                            ReleaseDate = "2019",
                            Title = "Parasite"
                        });
                });

            modelBuilder.Entity("MovieTown.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer");

                    b.Property<int>("Seat")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ScreeningId", "Row", "Seat")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MovieTown.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            MovieId = 1,
                            StartTime = new DateTime(2026, 1, 24, 16, 3, 24, 58, DateTimeKind.Utc).AddTicks(5927)
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            MovieId = 2,
                            StartTime = new DateTime(2026, 1, 24, 19, 3, 24, 58, DateTimeKind.Utc).AddTicks(6087)
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            MovieId = 3,
                            StartTime = new DateTime(2026, 1, 25, 10, 3, 24, 58, DateTimeKind.Utc).AddTicks(6089)
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 2,
                            MovieId = 4,
                            StartTime = new DateTime(2026, 1, 29, 4, 3, 24, 58, DateTimeKind.Utc).AddTicks(6091)
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            MovieId = 5,
                            StartTime = new DateTime(2026, 1, 27, 22, 3, 24, 58, DateTimeKind.Utc).AddTicks(6092)
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 2,
                            MovieId = 6,
                            StartTime = new DateTime(2026, 1, 25, 6, 3, 24, 58, DateTimeKind.Utc).AddTicks(6093)
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            MovieId = 7,
                            StartTime = new DateTime(2026, 1, 27, 2, 3, 24, 58, DateTimeKind.Utc).AddTicks(6093)
                        },
                        new
                        {
                            Id = 8,
                            CinemaId = 2,
                            MovieId = 8,
                            StartTime = new DateTime(2026, 1, 29, 6, 3, 24, 58, DateTimeKind.Utc).AddTicks(6094)
                        });
                });

            modelBuilder.Entity("MovieTown.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieTown.Models.Reservation", b =>
                {
                    b.HasOne("MovieTown.Models.Screening", "Screening")
                        .WithMany("Reservations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTown.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTown.Models.Screening", b =>
                {
                    b.HasOne("MovieTown.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTown.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTown.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("MovieTown.Models.Screening", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("MovieTown.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
